# include .env

# .PHONY: diff
# diff:
# 	atlas migrate diff --env gorm --var devUrl=${POSTGRESQL_URL}

# .PHONY: apply
# apply:
# 	atlas migrate apply --url ${POSTGRESQL_URL}

# .PHONY: rollback
# rollback:
# 	atlas migrate down --dir "file://migrations" --url ${POSTGRESQL_URL} --dev-url ${POSTGRESQL_URL}
